server:
 port: 8081
logging:
 level:
  root: info

spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/beneficiodb
  username: user
  password: password
  driver-class-name: org.postgresql.Driver
 jpa:
   hibernate:
    ddl-auto: none   # create, create-drop, update, validate, none
   properties:
    hibernate:
     format_sql: true
     dialect: org.hibernate.dialect.PostgreSQLDialect
   show-sql: true

 springdoc:
   paths-to-match: 
     - /**
   swagger-ui:
     use-root-path: true    
     path: /swagger-ui.html
     default-models-expand-depth: -1
     operations-sorter: alpha

 management:
   endpoints:
     web:
       exposure:
         include: 'health, info, metrics'
   endpoint:
     health:
       enabled: true
       show-details: always

 logging:
   #file:
    # name: ./data/logs/log-file.log  
   pattern:
     level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"

 ## Configuring info endpoint
 info:
   app:
     name: Backend Module
     description: Backend Module
     version: 1.0.0